secrets: secrets.yml
templates:
  torrent_server:
    transmission:
      host: localhost
      port: 9091
      path: '{{ secrets.transmission.path }}'
  tv:
    template: [ torrent_server ]
    include: [ series.yml ]

email:
  from: '{{ secrets.email.from }}'
  to: '{{ secrets.email.to }}'
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: '{{ secrets.email.smtp_username }}'
  smtp_password: '{{ secrets.email.smtp_password }}'
  smtp_tls: yes
  template: accepted

tasks:
  tv-rb-chat:
    rss: http://rss.bt-chat.com/?group=3
    template: tv
  tv-torrentz:
    rss: http://torrentz.eu/feed
    template: tv
  tv-extratorrent:
    rss: http://extratorrent.cc/rss.xml?cid=8
    template: tv
  tv-feedburner:
    rss: http://feeds.feedburner.com/eztv-rss-atom-feeds?format=xml
    template: tv
