secrets: secrets.yml
templates:
  tv:
    transmission:
      host: localhost
      port: 9091
      path: /media/i1000/downloads
    exists_series: /media/i1000/downloads
    series:
      - 12 Monkeys
      - Allegiance
      - Arrow
      - Backstrom
      - Banshee
      - Better Call Saul
      - Bitten
      - Bones
      - Brooklyn Nine-Nine
      - Castle (2009)
      - Constantine
      - Elementary
      - Forever
      - Grimm
      - Jimmy Fallon
      - Marvels Agent Carter
      - Person of Interest
      - Selfie
      - Stalker
      - State of Affairs
      - The Big Bang Theory
      - The Blacklist
      - The Daily Show
      - The Flash 2014
      - The Last Man On Earth
      - The Man In The High Castle
      - The Newsroom
      - True Detective
      - White Collar
      - iZombie
    quality: hdtv
email:
  from: '{{ secrets.email.from }}'
  to: '{{ secrets.email.to }}'
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: '{{ secrets.email.smtp_username }}'
  smtp_password: '{{ secrets.email.smtp_password }}'
  smtp_tls: yes
  template: accepted

tasks:
  tv-rb-chat:
    rss: http://rss.bt-chat.com/?group=3
    template: tv
  tv-torrentz:
    rss: http://torrentz.eu/feed
    template: tv
  tv-extratorrent:
    rss: http://extratorrent.cc/rss.xml?cid=8
    template: tv
  tv-feedburner:
    rss: http://feeds.feedburner.com/eztv-rss-atom-feeds?format=xml
    template: tv
